### ISSUE TITLE
Error load pretrained weight

### ISSUE THREAD

**Issue by duongvanbien13081999** [mantasu/sunglasses-detector#1]
Hi, I'm try run predict.py to test your weight, but i got the error:
"RuntimeError: Error(s) in loading state_dict for SunglassesClassifier:
Missing key(s) in state_dict: "base_model.features.0.0.weight", "base_model.features.0.1.weight", ...."

**Comment by mantasu** [comment]
Hi, the repository is being reworked and the models are being retrained. I expect this to be ready in a couple of weeks. But I will update the instructions on how to train personal models this week.

**Comment by mantasu** [comment]
You may want to switch to an older commit a couple of months back to test the old weights.

**Comment by mantasu** [comment]
Closing this cuz just released a pip package with retrained models. Models for other tasks will also be released sometime in the future.
