### ISSUE TITLE
classify sunglasses

### ISSUE THREAD

**Issue by kienld3049** [mantasu/sunglasses-detector#4]
Hello author, I really need a model to classify sunglasses (the same task you provided). Can you upload the code of this task earlier. I really appreciate that..Thank you so much

**Comment by mantasu** [comment]
Hi, you should be able to do that. Just install the current BETA version with pip and go through the examples in `README.md`. They show how to classify sunglasses. 

Note that all the interface at some point in the future will be updated, with better models, but that probably won't happen anytime soon.

**Comment by mantasu** [comment]
Sunglasses classification is currently implemented but will be updated soon.
