### ISSUE TITLE
Python Script is not working

### ISSUE THREAD

**Issue by manadopeee** [mantasu/sunglasses-detector#5]
I tried running this script

from glasses_detector import SunglassesClassifier

classifier = SunglassesClassifier(model_type="small", pretrained=True).eval()

classifier.predict(
    input_path="path/to/dir", 
    output_path="path/to/output.csv",
    label_type="int",
)

but it didn't work

so I fixed it like this.

from glasses_detector import SunglassesClassifier

classifier = SunglassesClassifier(base_model="small", pretrained=True).eval()

classifier.process(
    input_path="path/to/dir", 
    output_path="path/to/output.csv",
    label_type="int",
)

**Comment by mantasu** [comment]
Thanks, I'll take a look into this when reworking the package after Christmas~

**Comment by mantasu** [comment]
Fixed with #6
