### ISSUE TITLE
Eyeglass classifier 

### ISSUE THREAD

**Issue by RamitPahwa** [mantasu/sunglasses-detector#7]
Is the Eyeglass classifier available at the moment ?
Would it possible to share a single checkpoint for eyeglass classifier.

Thanks in advance!

**Comment by mantasu** [comment]
Sorry, only a sunglasses classifier is available now (however, it will not identify regular eyeglasses). It should not be too hard though to train your own model using a similar structure as for `SunglassesClassifier` (some Kaggle datasets would work).

But all the features should arrive by February, see #2.

**Comment by mantasu** [comment]
I've released some temporary weights that may help you. See #9~
