### ISSUE TITLE
Getting HTTP 404 when trying to download models

### ISSUE THREAD

**Issue by dhyey-dreamwave** [mantasu/sunglasses-detector#8]
Hello, 

I am having difficulty running the classifier locally. I'm getting a 404 error while using command line as well as in a Python script.  This is the URL it is trying to hit: 
`Downloading: "https://github.com/mantasu/glasses-detector/releases/download/eyeglasses_classifier_efficientnet_b0.pth"`

Is anyone else facing the same problem?

Alternatively, where can I find the different models that are used here?

**Comment by mantasu** [comment]
Hey, unfortunately, the eyeglasses model is not available yet. The only available ones are the sunglasses classifier and generic glasses segmenter.

As noted in #2 and #7, it will only be ready in February with a non-beta release.

**Comment by dhyey-dreamwave** [comment]
Hi. Thank you. I was looking for the Anyglasses classifier. But I guess we'll have to wait.

**Comment by mantasu** [comment]
I've released some temporary weights that may help you. See #9~
